apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-monitoring
  labels:
    app: ssl-monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ssl-monitoring
  template:
    metadata:
      labels:
        app: ssl-monitoring
    spec:
      containers:
      - name: ssl-monitoring
        image: ssl-monitoring:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ssl-monitoring-secrets
              key: database-url
        - name: APP_URL
          value: "https://ssl-monitoring-checking-ssl.d3.clouz.io"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: CORS_ORIGINS
          value: "http://localhost:3000,http://localhost:8080,https://ssl-monitoring-checking-ssl.d3.clouz.io,https://postgresql-checking-ssl.d3.clouz.io"
        - name: TEAMS_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: ssl-monitoring-secrets
              key: teams-webhook-url
              optional: true
        - name: SSL_TIMEOUT_SECONDS
          value: "10"
        - name: MAX_CONCURRENT_CHECKS
          value: "5"
        - name: PYTHONPATH
          value: "/app"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health/liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health/liveness
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
